apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pii-system-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: pii-redactor-controller

images:
  - name: controller
    newName: ghcr.io/bunseokbot/pii-redactor
    newTag: dev
