apiVersion: v1
kind: Service
metadata:
  name: {{ include "pii-redactor.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pii-redactor.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.controller.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "pii-redactor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
